### ISSUE TITLE
RedisJSONSerializer - cast error

### ISSUE THREAD

**Issue by jcarroyo** [welegan/RedisSessionProvider#12]
I'm applying your RedisSessionProvider to our project to improve it.
All was working fine until I realized that RedisJSONSerializer give us some problems.
The issue is when RedisJSONSerializer serialized a ComplexType (SerializeOne function).
It's storing fine, but when it's come time to deserialize is converting int type to long.

**Comment by MaKCbIMKo** [comment]
Joe,

I'm pretty sure, that this problem is not a problem of RedisJSONSerializer, but json.NET itself.
Here is a link to stackoverflow: http://stackoverflow.com/questions/8297541/how-do-i-change-the-default-type-for-numeric-deserialization
There is a description for this behavior...
